-- Inserción de datos para la tabla Productos
INSERT INTO PRODUCTOS (nombre, descripcion, imagen_url, precio, disponible, ubicacion) VALUES
('San Carlos de Bariloche', 'Explora el Parque Nacional Tierra del Fuego y viaja en el Tren del Fin del Mundo en Ushuaia', 'https://t4.ftcdn.net/jpg/03/59/04/93/360_F_359049346_S8EnaUo5xfEpMgjRh1cWbrDb5poVduKv.jpg', 300, TRUE, 'San Carlos de Bariloche'),
('Parque Nacional y Viaje en Tren al Fin del Mundo, Ushuaia', 'Explora el Parque Nacional Tierra del Fuego y viaja en el Tren del Fin del Mundo en Ushuaia', 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-720x480/0c/03/52/47.jpg', 300, TRUE, 'Ushuaia'),
('Bodega Trapiche, Mendoza', 'Visita la famosa bodega Trapiche en Mendoza y disfruta de degustaciones de vino', 'https://caminosdelvino.com/wp-content/uploads/2023/03/Rally-Bodegas-Trapiche-02.jpeg', 150, TRUE, 'Mendoza'),
('Excursión a Cataratas de Iguazú', 'Descubre la majestuosidad de las Cataratas de Iguazú, una de las maravillas naturales del mundo', 'https://elcomercio.pe/resizer/2ITamSMqTz3Ot8IrtHlNWls0Idc=/980x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/PFSTC2F2P5GSDB2OAN3ERHITCY.jpg', 200, TRUE, 'Cataratas de Iguazú'),
('Cerro de los 7 Colores, Jujuy', 'Admira el impresionante Cerro de los 7 Colores en Purmamarca, Jujuy', 'https://www.argentinaparamirar.com.ar/wp-content/uploads/2024/01/cerro-de-los-7-colores.jpg', 100, TRUE, 'Purmamarca'),
('Mini Trekking Glaciar Perito Moreno, El Calafate', 'Experimenta una caminata única sobre el glaciar Perito Moreno en El Calafate', 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/04/b1/f4.jpg', 180, TRUE, 'El Calafate'),
('Las Salinas Grandes, Salta y Jujuy', 'Explora las vastas y deslumbrantes Salinas Grandes en el norte de Argentina', 'https://agathauraviajes.tur.ar/wp-content/uploads/2020/01/Salinas-Grandes.jpg', 120, TRUE, 'Salta y Jujuy'),
('Tour para Pequeños Grupos en Buenos Aires', 'Descubre Buenos Aires en un tour personalizado para pequeños grupos', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/8d/5f/f9/caption.jpg?w=1200&h=-1&s=1', 80, TRUE, 'Buenos Aires');
